// <auto-generated />
using System;
using API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260505181532_corrigindo")]
    partial class corrigindo
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("API.Models.FormularioPedido", b =>
                {
                    b.Property<Guid>("CodigoPedido")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Bairro")
                        .HasColumnType("text");

                    b.Property<string>("Cep")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<string>("Complemento")
                        .HasColumnType("text");

                    b.Property<string>("Logradouro")
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(35)
                        .HasColumnType("character varying(35)");

                    b.Property<string>("Numero")
                        .HasColumnType("text");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)");

                    b.Property<string>("TipoEntrega")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TipoPagamento")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("CodigoPedido");

                    b.ToTable("FormulariosPedido");
                });

            modelBuilder.Entity("API.Models.Pedido", b =>
                {
                    b.Property<Guid>("IdPedido")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Concluido")
                        .HasColumnType("boolean");

                    b.Property<Guid>("FkCodigoPedido")
                        .HasColumnType("uuid");

                    b.Property<Guid>("FkIdPrato")
                        .HasColumnType("uuid");

                    b.Property<string>("Personalizacao")
                        .HasColumnType("text");

                    b.Property<int>("Quantidade")
                        .HasColumnType("integer");

                    b.HasKey("IdPedido");

                    b.HasIndex("FkCodigoPedido");

                    b.HasIndex("FkIdPrato");

                    b.ToTable("ItensPedido");
                });

            modelBuilder.Entity("API.Models.Prato", b =>
                {
                    b.Property<Guid>("IdPrato")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Acompanhamentos")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Descricao")
                        .HasColumnType("text");

                    b.Property<bool>("Disponivel")
                        .HasColumnType("boolean");

                    b.Property<string>("InfoIngredientes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NomePrato")
                        .IsRequired()
                        .HasMaxLength(35)
                        .HasColumnType("character varying(35)");

                    b.Property<decimal>("Preco")
                        .HasColumnType("decimal(8,2)");

                    b.Property<string>("UrlImagem")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdPrato");

                    b.ToTable("Pratos");
                });

            modelBuilder.Entity("API.Models.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("UsuariosAdm", (string)null);
                });

            modelBuilder.Entity("API.Models.Pedido", b =>
                {
                    b.HasOne("API.Models.FormularioPedido", "FormularioPedido")
                        .WithMany()
                        .HasForeignKey("FkCodigoPedido")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.Models.Prato", "Prato")
                        .WithMany()
                        .HasForeignKey("FkIdPrato")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FormularioPedido");

                    b.Navigation("Prato");
                });
#pragma warning restore 612, 618
        }
    }
}
